<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>topNameTech</name>
   <tag></tag>
   <elementGuidId>3c37c750-78c4-4b08-b8e2-fb57d902be56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.badge.badge-pill.badge-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UserInf']/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a1179a0e-dca6-4fb9-8d48-90ff5991d184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge badge-pill badge-secondary</value>
      <webElementGuid>49dc891f-466c-4213-91d5-7916b1f2afa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INGE T01</value>
      <webElementGuid>5d3a0094-03da-46c1-94f4-12a937092b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserInf&quot;)/ul[@class=&quot;nav navbar-nav ml-auto mr-1&quot;]/li[@class=&quot;nav-item dropdown nav-user-menu&quot;]/a[@class=&quot;nav-link dropdown-toggle&quot;]/span[@class=&quot;badge badge-pill badge-secondary&quot;]</value>
      <webElementGuid>f811425a-fe59-4725-9ab4-568450f013ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UserInf']/ul/li/a/span</value>
      <webElementGuid>dc2cb462-4881-4c24-899a-267bc94810cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy'])[1]/following::span[3]</value>
      <webElementGuid>3ea46bda-267f-42d6-97b2-9d0e577d8f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/preceding::span[1]</value>
      <webElementGuid>77965320-0796-4109-8813-af476a045c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/preceding::span[1]</value>
      <webElementGuid>a8dacd25-4fb2-4753-b3ee-f0a756a07b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INGE T01']/parent::*</value>
      <webElementGuid>134ed754-bca0-44e5-925f-422b17483045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>fd114a99-e558-45c4-896c-b05c4353fe33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'INGE T01' or . = 'INGE T01')]</value>
      <webElementGuid>29d32ac4-ca69-4d4d-ad1e-dd182feb5ce3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
